import { Header } from '@/shared/components'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<Header />
				{children}
			</body>
		</html>
	)
}
